name: Guiy-Example
version: "${plugin_version}"
author: Offz
main: com.mineinabyss.guiy.example.GuiyExamplePlugin
api-version: "1.20"

dependencies:
  server:
    Guiy:
      required: true
      load: BEFORE
      join-classpath: true
